batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 73
model_path: Models/ense480_project/202303121345
train_epochs: 1000
train_workers: 20
vocab: '#SFDsEmfj,o9t;&COa0PwINpJ!cuzLVk7A.T:M6HRg-''(ie53GlhxqQ)vbd1"84Y?rWBZ2nK
  Uy'
width: 1408
